package min.hearthstone.card.minion;

public enum MinionStateNAbility {
	NORMAL, FROZEN, TAUNT, DEVIENSHIELD, DONE, SLEEP, CHARGE, WINDFURY, STEALTH, CANT_ATTACK, POISONOUS, 
	
	BATTLECRY, ENRAGE, DEATHRATTLE, SECRET, 
	START_OF_YOUR, END_OF_YOUR, START_OF_OPPONENT, END_OF_OPPONENT, YOU_CAST, OPPONENT_CAST, COST, TAKES_DAMAGE,
	YOU_PLAY, OPPONENT_PLAY, OTHER_MINIONS_DIE
}
